# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ahci" "sd_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/9597d413-45ef-46b3-87a2-4578d4871786";
      fsType = "ext4";
    };

  swapDevices = [ { device = "/dev/disk/by-uuid/00b4aecc-00c0-4a72-8672-f51d5c28dc4d"; } ];

  nix.settings.max-jobs = lib.mkDefault 12;
}
